//Generated by Lightning Kite's Mirror plugin
//AUTOMATICALLY GENERATED AND WILL BE OVERRIDDEN IF THIS MESSAGE IS PRESENT
package com.lightningkite.kommon.string

import com.lightningkite.mirror.info.*
import kotlin.reflect.KClass
import kotlinx.serialization.*
import mirror.kotlin.*

object BackedByStringMirror : PolymorphicMirror<BackedByString>() {
    @Suppress("UNCHECKED_CAST")
    override val kClass: KClass<BackedByString> get() = BackedByString::class as KClass<BackedByString>
    override val modifiers: Array<Modifier> get() = arrayOf(Modifier.Interface, Modifier.Abstract)
    override val implements: Array<MirrorClass<*>> get() = arrayOf(AnyMirror)
    override val packageName: String get() = "com.lightningkite.kommon.string"
    override val localName: String get() = "BackedByString"
}
