//Generated by Lightning Kite's Mirror plugin
//AUTOMATICALLY GENERATED AND WILL BE OVERRIDDEN IF THIS MESSAGE IS PRESENT
package com.lightningkite.mirror.form.info

import com.lightningkite.mirror.info.*
import kotlin.reflect.KClass
import kotlinx.serialization.*
import mirror.kotlin.*

class FormEditOnlyMirror(
): MirrorAnnotation {
    override val annotationType: KClass<out Annotation> get() = FormEditOnly::class
    override fun asMap(): Map<String, Any?> = mapOf(
    )
}
