//Generated by Lightning Kite's Mirror plugin
//AUTOMATICALLY GENERATED AND WILL BE OVERRIDDEN IF THIS MESSAGE IS PRESENT
package com.lightningkite.krosslin.test.models

import com.lightningkite.kommon.string.Email
import com.lightningkite.lokalize.time.TimeStamp
import com.lightningkite.mirror.archive.database.Database
import com.lightningkite.mirror.archive.model.HasUuid
import com.lightningkite.mirror.archive.model.Uuid
import com.lightningkite.mirror.form.info.FormEditOnly
import com.lightningkite.mirror.form.info.FormHidden
import com.lightningkite.mirror.form.info.FormNeedsNoContext
import com.lightningkite.mirror.info.ThrowsTypes
import com.lightningkite.mirror.request.Request
import com.lightningkite.mirror.info.*
import kotlin.reflect.KClass
import kotlinx.serialization.*
import mirror.kotlin.*
import com.lightningkite.kommon.string.EmailMirror
import com.lightningkite.mirror.request.RequestMirror

object UserResetPasswordMirror : MirrorClass<User.ResetPassword>() {
    override val empty: User.ResetPassword get() = User.ResetPassword(
        email = EmailMirror.empty
    )
    @Suppress("UNCHECKED_CAST")
    override val kClass: KClass<User.ResetPassword> get() = User.ResetPassword::class as KClass<User.ResetPassword>
    override val modifiers: Array<Modifier> get() = arrayOf(Modifier.Data)
    override val packageName: String get() = "com.lightningkite.krosslin.test.models"
    override val localName: String get() = "User.ResetPassword"
    override val implements: Array<MirrorClass<*>> get() = arrayOf(RequestMirror(UnitMirror))
    override val owningClass: KClass<*>? get() = User::class
    
    val fieldEmail: Field<User.ResetPassword,Email> = Field(
        owner = this,
        index = 0,
        name = "email",
        type = EmailMirror,
        optional = false,
        get = { it.email },
        annotations = listOf<Annotation>()
    )
    
    override val fields: Array<Field<User.ResetPassword, *>> = arrayOf(fieldEmail)
    
    override fun deserialize(decoder: Decoder): User.ResetPassword {
        var emailSet = false
        var fieldEmail: Email? = null
        val decoderStructure = decoder.beginStructure(this)
        loop@ while (true) {
            when (decoderStructure.decodeElementIndex(this)) {
                CompositeDecoder.READ_ALL -> {
                    fieldEmail = decoderStructure.decodeSerializableElement(this, 0, EmailMirror)
                    emailSet = true
                    break@loop
                }
                CompositeDecoder.READ_DONE -> break@loop
                0 -> {
                    fieldEmail = decoderStructure.decodeSerializableElement(this, 0, EmailMirror)
                    emailSet = true
                }
                else -> {}
            }
        }
        decoderStructure.endStructure(this)
        if(!emailSet) {
            throw MissingFieldException("email")
        }
        return User.ResetPassword(
            email = fieldEmail as Email
        )
    }
    
    override fun serialize(encoder: Encoder, obj: User.ResetPassword) {
        val encoderStructure = encoder.beginStructure(this)
        encoderStructure.encodeSerializableElement(this, 0, EmailMirror, obj.email)
        encoderStructure.endStructure(this)
    }
}
